[package]
name = "rust-space-shooter"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = { version = "0.4.13", features = ["audio"] }
macroquad-particles = "0.2.2"

[profile.dev]
opt-level = 1

[profile.dev.package.'*']
opt-level = 3
